//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

int32_t g1 = 0;

// ------------------------ Functions -------------------------

// From module:   /root/pwn/calc.c
// Address range: 0x400870 - 0x400bc0
// Line range:    25 - 61
int main(int argc, char ** argv) {
    char buf[64]; // bp-116
    // 0x400870
    setvbuf((struct _IO_FILE *)*(int32_t *)g1, NULL, 2, 0);
    int32_t v1 = (int32_t)&buf; // 0x400920
    int32_t v2 = 128; // s2
    int32_t v3 = v1; // 0x4009909
    int32_t v4 = 128; // 0x400978
    // branch -> 0x400978
    int32_t v5; // 0x4009bc
    int32_t v6; // 0x4009bc15
    int32_t v7; // 0x4009d4
    int32_t v8; // 0x4009a8
    int32_t v9; // 0x400978
    while (true) {
        // 0x400978
        v9 = v4 < 2;
        v6 = v3;
        int32_t v10 = v4; // 0x4009b4
        char v11;
        int32_t v12; // v1
        int32_t v13; // 0x4009a4
        if (v4 >= 2) {
            // 0x400984
            v12 = v3;
            v13 = v3;
            v11 = 0;
            // branch -> 0x4009a4
          lab_0x4009a4_3:
            // 0x4009a4
            *(char *)v13 = v11;
            v8 = v2 - 1;
            v2 = v8;
            int32_t v14 = v9; // 0x4009ac
            int32_t v15 = v12 + 1; // 0x4009b0
            if (v14 == 10) {
                v6 = v15;
                v9 = v14;
                // break -> 0x4009b4
                break;
            }
            v3 = v15;
            v4 = v8;
            // continue -> 0x400978
            continue;
        }
        // 0x4009b4
        v7 = v9;
        if (v10 != 0) {
            v5 = v6;
          lab_0x4009bc_2:
            // 0x4009bc
            *(char *)v5 = 0;
            v7 = v9;
            // branch -> 0x4009c0
        }
      lab_0x4009c0:
        // 0x4009c0
        if (v7 == 0) {
            // 0x4009e0
            // branch -> 0x400ab4
        } else {
            // 0x4009e0
            *(char *)v7 = 0;
            int32_t v16 = v9;
            if (v16 != 0) {
                // 0x400a50
                v2 = 128;
                if (2 * v16 == 0x133a05e) {
                    // 0x400ba8
                    // branch -> 0x400adc
                    // 0x400adc
                    return 0;
                }
                // 0x400ab4
                v12 = v1;
                char v17 = v16;
                if (v16 > -1) {
                    v13 = v1;
                    v11 = v17;
                    goto lab_0x4009a4_3;
                }
                // 0x400adc
                return 0;
            }
            // 0x400ab4
            v2 = 128;
            v12 = v1;
            v13 = v1;
            v11 = 0;
            // branch -> 0x4009a4
            goto lab_0x4009a4_3;
        }
        // 0x400ab4
        v2 = 128;
        v12 = v1;
        v13 = v1;
        v11 = 0;
        // branch -> 0x4009a4
        goto lab_0x4009a4_3;
    }
    // 0x4009b4
    if (v8 == 0) {
        v7 = v9;
        goto lab_0x4009c0;
    }
    v5 = v6;
    goto lab_0x4009bc_2;
}

// --------------- Dynamically Linked Functions ---------------

// int setvbuf(FILE * restrict stream, char * restrict buf, int modes, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.5)
// Detected language: C
// Detected functions: 1
// Decompilation date: 2018-09-18 04:08:19
